export const mockUsers = {
    username1: {
      name: "Jane Doe",
      email: "janedoe1995@gmail.com",
      userIcon: "mock-user.png",
      ownedGrids: ["gridID1", "gridID2"],
      likedPosts: ["postID1", "postID2"],
      followedBy: ["username26", "username3", "username4", "username5", "username7", "username9"],
      follows: ["username22", "username3", "username14", "username65"],
      likes: 150,
    },
    username2: {
      name: "John Smith",
      email: "johnsmith1988@gmail.com",
      userIcon: "mock-user1.png",
      ownedGrids: ["gridID3", "gridID4"],
      likedPosts: ["postID3", "postID4"],
      followedBy: ["username1", "username4", "username6"],
      follows: ["username5", "username7", "username9", "username10", "username11"],
      likes: 200,
    },
    username3: {
      name: "Emily Johnson",
      email: "emilyjohnson1990@gmail.com",
      userIcon: "mock-user2.png",
      ownedGrids: ["gridID5"],
      likedPosts: ["postID5", "postID6"],
      followedBy: ["username2", "username4"],
      follows: ["username8", "username12", "username13"],
      likes: 180,
    },
    username4: {
      name: "Michael Brown",
      email: "michaelbrown1985@gmail.com",
      userIcon: "mock-user3.png",
      ownedGrids: ["gridID6", "gridID7"],
      likedPosts: ["postID7", "postID8"],
      followedBy: ["username1", "username3"],
      follows: ["username15", "username16", "username17", "username18"],
      likes: 220,
    },
    username5: {
      name: "Sarah Williams",
      email: "sarahwilliams1992@gmail.com",
      userIcon: "mock-user.png",
      ownedGrids: ["gridID8"],
      likedPosts: ["postID9", "postID10"],
      followedBy: ["username2", "username4", "username6", "username8"],
      follows: ["username19", "username20", "username21"],
      likes: 190,
    },
  };
    
    export const mockGrids = {
      gridID1: {
          content: "mock-img1.jpg",
          title: "Grid 1",
          isPrivate: true,
          author: "username1",
          likes: ["likeID1", "likeID2", "likeID3"],
          comments: ["commentID1", "commentID2", "commentID3"],
          postedDate: "20.04.2024 12:26",
        },
        gridID2: {
          content: "mock-img2.jpg",
          title: "Grid 2",
          isPrivate: false,
          author: "username2",
          likes: ["likeID4"],
          comments: ["commentID5", "commentID6"],
          postedDate: "21.04.2024 14:30",
        },
        gridID3: {
          content: "mock-img3.jpg",
          title: "Grid 3",
          isPrivate: true,
          author: "username3",
          likes: [],
          comments: ["commentID7"],
          postedDate: "22.04.2024 15:45",
        },
        gridID4: {
          content: "mock-img4.png",
          title: "Grid 4",
          isPrivate: false,
          author: "username4",
          likes: ["likeID5", "likeID6"],
          comments: [],
          postedDate: "23.04.2024 16:00",
        },
        gridID5: {
          content: "mock-img5.jpg",
          title: "Grid 5",
          isPrivate: true,
          author: "username5",
          likes: [],
          comments: [],
          postedDate: "24.04.2024 17:30",
      },
    };
  
  export const mockComments = {
      commentID1: {
          grid: "gridID1",
          author: "username2",
          content: "Nice grid!",
          date: "20.04.2024 03:34",
        },
        commentID2: {
          grid: "gridID2",
          author: "username3",
          content: "Great layout!",
          date: "21.04.2024 13:12",
        },
        commentID3: {
          grid: "gridID3",
          author: "username4",
          content: "Awesome!",
          date: "22.04.2024 19:45",
        },
        commentID4: {
          grid: "gridID4",
          author: "username5",
          content: "Love this!",
          date: "23.04.2024 16:33",
        },
        commentID5: {
          grid: "gridID5",
          author: "username6",
          content: "Impressive work!",
          date: "24.04.2024 09:23",
        },
};
